spring.application.name=login-ms
server.port=${SERVER_PORT:1010}

jwt.private.key=classpath:app_pkcs8.key
jwt.public.key=classpath:app_public.key

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/login-ms}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:test123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:victorneves596@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hyct lmst vilb qvrv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_TRUST_HOST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
logging.level.org.springframework.security=DEBUG
spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqps://ygnuaaqx:hYwwUBiP2GIW6iWZ7LKuzklgOa5HH8-G@jackal.rmq.cloudamqp.com/ygnuaaqx}
spring.rabbitmq.username=${RABBITMQ_USERNAME:ygnuaaqx}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:hYwwUBiP2GIW6iWZ7LKuzklgOa5HH8-G}
broker.queue.email.name=${BROKER_QUEUE_EMAIL:email-queue}
broker.queue.user.data.name=${BROKER_QUEUE_USER_DATA:user-data}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.security=DEBUG