spring.application.name=login-ms
server.port=${SERVER_PORT:1010}

jwt.private.key=classpath:app_pkcs8.key
jwt.public.key=classpath:app_public.key

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/login-ms}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:test123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}
broker.queue.email.name=${BROKER_QUEUE_EMAIL:email-queue}
broker.queue.user.data.name=${BROKER_QUEUE_USER_DATA:user-data}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
