spring.application.name=painel-ms
server.port=${SERVER_PORT:1013}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bankapp}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:test123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

jwt.private.key=classpath:app_pkcs8.key
jwt.public.key=classpath:app_public.key

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}
broker.queue.email.name=${BROKER_QUEUE_EMAIL:email-queue}
broker.queue.user.data.name=${BROKER_QUEUE_USER_DATA:user-data}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
