spring.application.name=email-sender-ms
server.port=1012

spring.rabbitmq.addresses=amqps://ygnuaaqx:hYwwUBiP2GIW6iWZ7LKuzklgOa5HH8-G@jackal.rmq.cloudamqp.com/ygnuaaqx

broker.queue.email.name=email-queue
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victorneves596@gmail.com
spring.mail.password=jtpr klly mvgq rsep
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000