spring.application.name=email-sender-ms
server.port=${SERVER_PORT:1012}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}
broker.queue.email.name=${BROKER_QUEUE_EMAIL:email-queue}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_TRUST_HOST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
