spring.application.name=email-sender-ms
server.port=1012

spring.rabbitmq.addresses=amqps://oznfnirl:TFQWoQuB20-xY--miorBBD4BkWVScN8K@beaver.rmq.cloudamqp.com/oznfnirl

broker.queue.email.name=email-queue

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victorneves596@gmail.com
spring.mail.password=jtpr klly mvgq rsep
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true